[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src"]

[contracts]
vote = ["src/voting.cairo"]
account = ["src/erase/1.cairo"]

[profile.devnet.deploy]
gateway-url = "http://127.0.0.1:5050/"
chain-id = "1"

[profile.testnet.deploy]
network = "testnet"

[profile.mainnet.deploy]
network = "alpha-mainnet"
